### ISSUE TITLE
unable run server project getting error

### ISSUE THREAD

**Issue by krishantalwar** [prolinkinfo/InsuranceProCRM#1]
I have install the npm 
and 
create the .env file with 

SECRET_KEY = abc123456xyz 
DB_URL = mongodb://localhost:27017/ 
PORT = 5000
DB_NAME = Demo

TypeError: Function.prototype.apply was called on undefined, which is a undefined and not a function
    at Object.<anonymous> (E:\aman sir\InsuranceProCRM\server\index.js:2:18)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)

Node.js v21.4.0
[nodemon] app crashed - waiting for file changes before starting...

**Comment by krishantalwar** [comment]
can you pls help me run the project locally?

**Comment by prolinkinfo** [comment]
replace DB_URL 
mongodb://localhost:27017/    ----->    mongodb://127.0.0.1:27017

**Comment by krishantalwar** [comment]
#I try to change. but it does not work getting the same error.
  mongodb://127.0.0.1:27017

![image](https://github.com/prolinkinfo/InsuranceProCRM/assets/32428642/b75926b9-ee67-4417-ab59-3ae1dd3256df)



#In index.js 
![image](https://github.com/prolinkinfo/InsuranceProCRM/assets/32428642/1d0d76b8-88c1-4ff4-ab3f-f632620c2ac0)


#My MongoDB runs at 
mongodb://localhost:27017

![image](https://github.com/prolinkinfo/InsuranceProCRM/assets/32428642/1c9d5b2f-3af2-4f31-ae58-98879632be55)

**Comment by prolinkinfo** [comment]
This is node js version issue
please change node version  
use this version 18.16.0 or 20.11.1
